### PR TITLE
[#25] Simple filtering by filename +  L&F updates

### PR DESCRIPTION
**Pull request by sawickil**
These changes do not affect mercurial repos
screenshot-localhost 8080 2015-12-06 11-31-16

### CODE REVIEW

**Comment by yu55** [comment]
Please move results counter to the bottom of page. The results counter is a nice feature but for end user it's not as important as results themselves,.

**Comment by sawickil** [comment]
Dont you think it's good to know there is lots of lines allowing user to limit the result by more narrow search conditions? Sometimes it's just good to know how many matches there are instead of viewing all of them. It's rather a basic feature of all searches on the web which show some numbers to the end user. The counter on the bottom is quite useless;)

**Comment by yu55** [comment]
Not sure about this. Counter is also taking lots of screen area which could be used to present raw results.
IMO most important for end users are search results, which should be clear, readable, pure information without noise, easy to copy etc. 
OK - lets try with your design, but will see what other users will say.

**Comment by sawickil** [comment]
you're completely right...that's why I'm planning to add hide/show feature
for that filtering section (repos + filters + ...)

2015-12-06 12:26 GMT+01:00 Marcin P <notifications@github.com>:

**Pull request merged**
